mod day01;
mod day02;
mod day03;
mod day04;
mod day05;
mod day06;
mod day07;
mod day08;
// mod day09;
// mod day10;
// mod day11;
// mod day11;
mod utils;

fn main() {
    println!("Advent of Code 2025 Rust \n");
    // println!("Day 1:");
    // day01::solve();
    // println!("Day 2:");
    // day02::solve();
    // println!("Day 3:");
    // day03::solve();
    // println!("Day 4:");
    // day04::solve();
    // println!("Day 5:");
    // day05::solve();
    // println!("Day 6:");
    // day06::solve();
    // println!("Day 7:");
    // day07::solve();
    println!("Day 8:");
    day08::solve();
    // println!("Day 9:");
    // day09::solve();
    // println!("Day 10:");
    // day10::solve();
    // println!("Day 11:");
    // day11::solve();
    // println!("Day 12:");
    // day12::solve();
}
